### ISSUE TITLE
remove `as XXXX` of TypeScript

### ISSUE THREAD

**Issue by ikemo3** [ikemo3/gossip-site-blocker#203]

**Comment by vibh1103** [comment]
Hi @ikemo3 can i pick this task ?

**Comment by ikemo3** [comment]
@vibh1103
Yes, I have no plans to pick this task soon.

**Comment by vibh1103** [comment]
can you please add hacktoberfest label and also assigned to me ?

**Comment by ikemo3** [comment]
@vibh1103 

Assigned. I've added "hacktoberfest" to the repository topic, so that should be all I have to do for now.

> [PARTICIPATING] YOUR PR/MRS MUST BE IN A REPO TAGGED WITH THE “HACKTOBERFEST” TOPIC, OR HAVE THE “HACKTOBERFEST-ACCEPTED” LABEL.
https://hacktoberfest.com/participation/

**Comment by vibh1103** [comment]
Thanks

**Comment by vibh1103** [comment]
@ikemo3 Please review the PR

**Comment by ikemo3** [comment]
@vibh1103 

Hmm...
At least, this change is not what I intended.
Type assertions are not safe.
That's why I created this issue.
I think type guard is the better solution.

**Comment by vibh1103** [comment]
Ok I'll refactor the code and add null checks ? @ikemo3

**Comment by ikemo3** [comment]
@vibh1103 

The direction is correct. However, since the changes vary depending on the code,
I prefer to process many small Pull Requests instead of doing everything in one Pull Request.

Especially if it's for hacktoberfest.

**Comment by vibh1103** [comment]
Ok then we will do one thing let me do it in subtasks PR's according to the file so that you can easily review and the if any of one is Breaking we can easily revert?

Tell me if I can do in that way ?

**Comment by ikemo3** [comment]
@vibh1103 

Of course, you can proceed in that way.
Please include a link to this issue number in the PR, but avoid using "closes".

**Comment by vibh1103** [comment]
Thanks for confirmation

**Comment by vibh1103** [comment]
Hi @ikemo3 

These are the following files and corresponding PR's 
1. google_news_section_with_header.ts (https://github.com/ikemo3/gossip-site-blocker/pull/930)
2. google_news_result.ts (https://github.com/ikemo3/gossip-site-blocker/pull/929)
3. google_search_movie.ts (https://github.com/ikemo3/gossip-site-blocker/pull/931)
4. appbar.ts (https://github.com/ikemo3/gossip-site-blocker/pull/932)
5. dialog.ts (https://github.com/ikemo3/gossip-site-blocker/pull/933)
6. options.ts (https://github.com/ikemo3/gossip-site-blocker/pull/934)
7. popup.ts (https://github.com/ikemo3/gossip-site-blocker/pull/935)
8. recommend.ts
9. banned_word.ts
10. export.ts
11. import.ts
12. regexp.ts
13. banned_words.ts
14. blocked_sites.ts
15. regexp_repository.ts

**Comment by vibh1103** [comment]
Hi @ikemo3 

These are the following files and corresponding PR's 
1. google_news_section_with_header.ts (#930)
2. google_news_result.ts (#929)
3. google_search_movie.ts (#931)
4. appbar.ts (#932)
5. dialog.ts (#933)
6. options.ts (#934)
7. popup.ts (#935)
8. regexp_repository.ts (#936)
9. banned_word.ts (#937)
10. export.ts (#938)
11. import.ts (#939)
12. regexp.ts (#940)
13. banned_words.ts (#941)
14. blocked_sites.ts (#942)

**Comment by ikemo3** [comment]
@vibh1103 

I reviewed all and approved those with no problems.
For the remaining items, please fix to throw an error when the element is not found, similar to #932.

**Comment by vibh1103** [comment]
@ikemo3  
I made the changes according to under please suggest if any other changes required on remaining PR's

**Comment by ikemo3** [comment]
@vibh1103 

Please use early returns to minimize deep nesting and make the diffs easier to read.
However, I've approved #938 since the changes there are minimal to begin with.

**Comment by vibh1103** [comment]
ok let made those changes

**Comment by ikemo3** [comment]
@vibh1103 

All Pull Requests have been merged. Thank you, good job. 🎉

**Comment by vibh1103** [comment]
Thanks for your support @ikemo3
