### ISSUE TITLE
Is there a way to donate?

### ISSUE THREAD

**Issue by YoshinoriN** [ikemo3/gossip-site-blocker#45]
Thank you very very much for awesome extension. 
I really appreciate your extension. Is there a way to donate?

**Comment by ikemo3** [comment]
Of course, donations are welcome :)

I'm considering the following method.
(Please let me know if you have any other recommended methods.)

* Amazon
* PayPal
* GitHub Sponsors

I'll let you know when the preparation is finished.

**Comment by YoshinoriN** [comment]
Thank you :)

> Please let me know if you have any other recommended methods.

Anything Okay. But, if the Amazon gift card is OK with you, I will send it to your GitHub profile email :)

**Comment by ikemo3** [comment]
> Anything Okay. But, if the Amazon gift card is OK with you, I will send it to your GitHub profile email :)
Yes, that's fine. Thank you!

**Comment by YoshinoriN** [comment]
I sent an Amazon gift card to you.
I sincerely appreciate you and your awesome extension :)
