### ISSUE TITLE
`Search in English` doesn't work when the url has an anker / URLにアンカーが含まれる場合に「英語で検索」が機能しない

### ISSUE THREAD

**Issue by takumi1001** [ikemo3/gossip-site-blocker#687]
## Describe the bug

`Search in English` dosen't work when the url of the Google search result has an anker.
e.g.) https://www.google.com/search?q=test&rlz=1C1TKQJ_jaJP998JP998&oq=test&aqs=chrome..69i57j0i433i512l2j69i60j69i61j69i65j69i61j69i65.773j0j9&sourceid=chrome&ie=UTF-8#bsht=CgVic2hocBIECAQwAQ

I think that's because Google added the  `#bsht=...`  anker tag at the search result URL recently. Therefore the URL params `&gl=us&hl=en` which are add to the end of URL doesn't work (URL params have to be before an anker tag as we know).

## To Reproduce

1. Search any keywords on the Google Chrome.
2. Click on 'Search in English'.

## Expected behavior

`&gl=us&hl=en` is added before the anker `#bsht=...`.

## Screenshots

I think it is not necessary.

## Desktop (please complete the following information):

 - OS: Windows and macOS
 - Browser: Chrome
 - Version: latest

## Additional context

　いつも愛用させていただいています。takumi1001と申します。突然issueを立ててしまい申し訳ありません。
　「英語で検索」機能を非常に重宝していたのですが、先日から機能しなくなってしまったために、原因を少し調べ報告させていただきました。
　お役に立てば幸いです。

**Comment by ikemo3** [comment]
I confirmed. I'll fix it.

確認できました。修正しますー。

**Comment by takumi1001** [comment]
ありがとうございます！m(_ _)m

**Comment by ikemo3** [comment]
次のバージョンで修正されますー。

**Comment by takumi1001** [comment]
ありがとうございます！！
